### ISSUE TITLE
NaN Values in A Matrix with Large Grid Size in curve2coeff

### ISSUE THREAD

**Issue by Peter-sth** [HadrienNU/better_kan#1]
Using the example program **symbolic_regression.py** as a reference: when the grid_size in build_splines_layers is set too large (e.g., 600), the A matrix in curve2coeff within layers.py results in NaN values, causing a calculation error. However, with the same grid_size value, the original efficient_kan can compute normally. I hope the author can address this issue in the next version.

**Comment by HadrienNU** [comment]
It does run for grid_size=600 in my computer. Could you provide more details? Did you use cuda or run the scipt on the cpu?

**Comment by Peter-sth** [comment]
When I attempt to read 4-input 2-output data from my Excel sheet, the following error occurs:

`Intel MKL ERROR: Parameter 4 was incorrect on entry to SGELSY.
Intel MKL ERROR: Parameter 4 was incorrect on entry to SGELSY.
Intel MKL ERROR: Parameter 4 was incorrect on entry to SGELSY.
Intel MKL ERROR: Parameter 4 was incorrect on entry to SGELSY.
Traceback (most recent call last):
... (traceback details)
RuntimeError: false INTERNAL ASSERT FAILED at "..\\aten\\src\\ATen\\native\\BatchLinearAlgebra.cpp":1540, please report a bug to PyTorch. torch.linalg.lstsq: (Batch element 0): Argument 4 has illegal value. Most certainly there is a bug in the implementation calling the backend library.
Process finished with exit code 1
`
My Excel sheet processing code is as follows:
file_path = r'testdata.xlsx'  # Replace with your Excel file path
df = pd.read_excel(file_path)

# Extract input data (first four columns)
`input_data = df.iloc[:, :4].values
input_data = np.log(input_data + 1)

# Extract output data (last two columns)
output_data = df.iloc[:, 4:].values

print(input_data.shape, output_data.shape)

X_train, X_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.2, random_state=16)

dataset = {
    "train_input": torch.tensor(X_train, dtype=torch.float32),
    "test_input": torch.tensor(y_train, dtype=torch.float32),
    "train_label": torch.tensor(X_test, dtype=torch.float32),
    "test_label": torch.tensor(y_test, dtype=torch.float32)
}`
The maximum value in the input data is 500, and the minimum value is 0. All output data values are negative, with nine decimal places.I have checked the processed data, and there are no NaN values or infinite values.

Here is my code for defining and training the model:
`model = KAN(build_splines_layers([4, 5, 2], grid_size=900, fast_version=False))


# f = lambda x: torch.exp(torch.sin(torch.pi * x[:, [0]]) + x[:, [1]] ** 2)
# dataset = create_dataset(f, n_var=2)
# print(dataset["train_input"].shape, dataset["train_label"].shape)


model(dataset["train_input"], update_grid=True)`

**Comment by Peter-sth** [comment]
> It does run for grid_size=600 in my computer. Could you provide more details? Did you use cuda or run the scipt on the cpu?



> It does run for grid_size=600 in my computer. Could you provide more details? Did you use cuda or run the scipt on the cpu?

## When I attempt to read 4-input 2-output data from my Excel sheet, the following error occurs:

`Intel MKL ERROR: Parameter 4 was incorrect on entry to SGELSY.
Intel MKL ERROR: Parameter 4 was incorrect on entry to SGELSY.
Intel MKL ERROR: Parameter 4 was incorrect on entry to SGELSY.
Intel MKL ERROR: Parameter 4 was incorrect on entry to SGELSY.
Traceback (most recent call last):
... (traceback details)
RuntimeError: false INTERNAL ASSERT FAILED at "..\\aten\\src\\ATen\\native\\BatchLinearAlgebra.cpp":1540, please report a bug to PyTorch. torch.linalg.lstsq: (Batch element 0): Argument 4 has illegal value. Most certainly there is a bug in the implementation calling the backend library.
Process finished with exit code 1
`
## Excel Sheet Processing Code
`file_path = r'testdata.xlsx' 
df = pd.read_excel(file_path)

# Extract input data (first four columns)
input_data = df.iloc[:, :4].values
input_data = np.log(input_data + 1)

# Extract output data (last two columns)
output_data = df.iloc[:, 4:].values

print(input_data.shape, output_data.shape)

X_train, X_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.2, random_state=16)

dataset = {
    "train_input": torch.tensor(X_train, dtype=torch.float32),
    "test_input": torch.tensor(y_train, dtype=torch.float32),
    "train_label": torch.tensor(X_test, dtype=torch.float32),
    "test_label": torch.tensor(y_test, dtype=torch.float32)
}
`
The maximum value in the input data is 500, and the minimum value is 0. All output data values are negative, with nine decimal places. I have checked the processed data, and there are no NaN values or infinite values.

## Model Definition and Training Code
`import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from better_kan import KAN, build_splines_layers, plot, train
from better_kan.symbolic import Symbolic_KANLayer

# Read data from Excel file
file_path = r'testdata.xlsx'  
df = pd.read_excel(file_path)

# Extract input data (first four columns)
input_data = df.iloc[:, :4].values
input_data = np.log(input_data + 1)

# Extract output data (last two columns)
output_data = df.iloc[:, 4:].values

print(input_data.shape, output_data.shape)

X_train, X_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.2, random_state=16)

dataset = {
    "train_input": torch.tensor(X_train, dtype=torch.float32),
    "test_input": torch.tensor(y_train, dtype=torch.float32),
    "train_label": torch.tensor(X_test, dtype=torch.float32),
    "test_label": torch.tensor(y_test, dtype=torch.float32)
}

# Define the model
model = KAN(build_splines_layers([4, 5, 2], grid_size=5, fast_version=False))

# Train the model
results = train(model, dataset, opt="LBFGS", steps=60, update_grid=True, lamb=0.05)

# Plot training results
plt.figure()
plt.plot(results["train_loss"])
plt.plot(results["test_loss"])
plt.plot(results["reg"])
plt.legend(["train", "test", "reg"])
plt.ylabel("RMSE")
plt.xlabel("step")
plt.yscale("log")
plt.show()

# Prune the model
new_model = model.prune(mode="auto")
new_model(dataset["test_input"])

# Plot the pruned model
plot(new_model, title="KAN after pruning", tick=False)
plt.show()`

**Comment by HadrienNU** [comment]
You should try with sbasis_trainable=False option for build_splines_layers
